package lib

import (
	"bytes"
	"html/template"
	"io/ioutil"
	"os"
	"strings"

	logging "github.com/op/go-logging"
)

type Values struct {
	ImageTag             string
	ServiceMap           []string `yaml:"ServiceMap"`
	Env                  map[string]string
	CloudFormationValues map[string]string `yaml:"CloudFormationValues"`
	PackageID            string
	Deployment           string
}

//NewValues Value factory
func NewValues(packageId string, deploy string, imageTag string, env map[string]string) *Values {
	v := Values{
		PackageID:  packageId,
		Deployment: deploy,
		ImageTag:   imageTag,
		Env:        env,
	}
	return &v
}

//Write runs the Value object through the YAML template and writes the output to a autogenerated/values.staging.<packageId>.yaml file
func (v *Values) Write(logger logging.Logger) string {
	basePath := GetReleasePath()
	fileMode := os.FileMode(0777)
	fileName := "values.staging." + v.PackageID + ".yaml"
	autogenPath := basePath + "/" + v.Deployment + "/autogenerated/"
	if !pathExists(autogenPath) {
		os.Mkdir(autogenPath, fileMode)
	}
	valuesPath := autogenPath + fileName
	logger.Infof("Creating: %s", fileName)
	logger.Infof("Created values file %s", valuesPath)

	stagingYaml := v.GetStagingYaml()
	logger.Debugf("%s", stagingYaml)
	err := ioutil.WriteFile(valuesPath, []byte(stagingYaml), fileMode)
	if err != nil {
		panic(err)
	}
	return valuesPath
}

func (v *Values) GetStagingYaml() string {
	funcs := template.FuncMap{
		"ToEnv": func(s string) string {
			s = strings.Replace(s, "-", "_", -1)
			return strings.ToUpper(s) + "_HOST"
		},
	}
	tmpl, err := template.New("values").Funcs(funcs).Parse(`

##################################################################
##                                                              ##
##  Autogenerated file. Changes made here will be overwritten.  ##
##                                                              ##
##################################################################

Boatswain:
  Active: true
  ImageTag: "{{.ImageTag}}"
  ServiceEnv:
    {{- range $key, $value := .Env }}
    {{ $key | ToEnv }}: {{ $value }}
	{{- end }}
  CloudFormationValues:
    {{- range $key, $value := .CloudFormationValues }}
    {{ $key }}: {{ $value }}
    {{- end }}

`)
	var doc bytes.Buffer
	err = tmpl.Execute(&doc, v)
	s := doc.String()
	if err != nil {
		panic(err)
	}
	return s
}

func pathExists(dirPath string) bool {
	_, err := os.Stat(dirPath)
	return !os.IsNotExist(err)

}
