// Copyright © 2017 MedBridge Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"bufio"
	"bytes"
	"fmt"
	"html/template"
	"io/ioutil"
	"os"
	"os/exec"
	"strings"

	yaml "gopkg.in/yaml.v2"

	"github.com/medbridge/mocking/factories"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var build = Build{}
var branchName string
var serviceMapName string
var serviceMapConfig ServiceMapConfig
var serviceMap ServiceMap

type StagingValuesYAML struct {
	ImageTag   string
	ServiceMap []string `yaml:"ServiceMap"`
	Env        map[string]string
}

// stageCmd represents the stage command
var stageCmd = &cobra.Command{
	Use:   "stage [push|delete]",
	Short: "A brief description of your command",
	Long:  ``,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Printf("Use boatswain stage [push|delete]")
	},
}

var stagePushCmd = &cobra.Command{
	Use:   "push [appnames] [domain]",
	Short: "Push an application(s) to staging",
	Long: `Push an application or bundle of applications to staging

	`,
	Run: func(cmd *cobra.Command, args []string) {
		RunStagePush(args)
	},
}

var stageDeleteCmd = &cobra.Command{
	Use:   "delete [appnames] [domain]",
	Short: "Delete an application(s) from staging",
	Long: `Delete an application or bundle of applications from staging
	
	`,
	Run: func(cmd *cobra.Command, args []string) {
		RunStageDelete(args)
	},
}

func init() {
	RootCmd.AddCommand(stageCmd)
	stageCmd.AddCommand(stagePushCmd, stageDeleteCmd)
}

func RunStagePush(args []string) {
	if len(args) != 2 {
		fmt.Printf("Unexpected number of args. Expected 2, got %c", len(args))
		return
	}
	getServiceMap()
	serviceMapName = args[0]
	branchName = args[1]

	config := Config{}
	configPath := viper.ConfigFileUsed()
	yamlFile, _ := ioutil.ReadFile(configPath)
	yaml.Unmarshal(yamlFile, &config)

	selectedBuilds := getSelectedBuilds(config)

	for _, build := range selectedBuilds {
		imageTag := runBuild(build)
		env := convertMapToEnvVars(serviceMap)

		stagingYaml := StagingValuesYAML{
			ImageTag: imageTag,
			Env:      env,
		}

		yaml := getStagingYaml(stagingYaml)

		fmt.Printf("%s", yaml)
		valuesPath := createValuesFile(build, config, yaml)
		runRelease(build, valuesPath)
		genIngress(build)
	}
}

func runRelease(build Build, valuesFile string) {

	args := []string{build.Name}
	options := ReleaseOptions{
		Environment:       "staging",
		DryRun:            false,
		Namespace:         "default",
		Packfile:          valuesFile,
		Xdebug:            false,
		NoExecute:         false,
		PackageIDOverride: branchName,
	}
	RunRelease(args, options)
}

func runBuild(build Build) string {
	cmdName := "/bin/bash"
	cmdArgs := []string{build.Path, "push"}

	targetsString := build.Targets
	targets := strings.Split(targetsString, ",")

	if len(targets) > 0 {
		for _, target := range targets {
			cmdArgs = append(cmdArgs, target)
		}
	}
	os.Chdir(build.Rootpath)
	cmd := exec.Command(cmdName, cmdArgs...)

	//https://nathanleclaire.com/blog/2014/12/29/shelled-out-commands-in-golang/
	cmdReader, err := cmd.StdoutPipe()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating StdoutPipe for Cmd", err)
		os.Exit(1)
	}

	scanner := bufio.NewScanner(cmdReader)
	go func() {
		for scanner.Scan() {
			fmt.Printf("build.sh | %s\n", scanner.Text())
		}
	}()

	err = cmd.Start()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error starting Cmd", err)
		os.Exit(1)
	}

	err = cmd.Wait()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error waiting for Cmd", err)
		os.Exit(1)
	}

	sha := getGitCommitSha(build)
	return string(sha[:])
}

func getGitCommitSha(build Build) []byte {
	os.Chdir(build.Rootpath)
	cmdName := "git"
	cmdArgs := []string{"show", "-s", "--pretty=format:%h"}
	out, err := exec.Command(cmdName, cmdArgs...).CombinedOutput()
	if err != nil {
		panic(err)
	}
	return out
}

func printWrapper(msg string) {
	fmt.Printf("boatswain | %s\n", msg)
}

func getStagingYaml(yaml StagingValuesYAML) string {
	funcs := template.FuncMap{
		"ToEnv": func(s string) string {
			s = strings.Replace(s, "-", "_", -1)
			return strings.ToUpper(s) + "_HOST"
		},
	}
	tmpl, err := template.New("values").Funcs(funcs).Parse(`

##################################################################
##                                                              ##
##  Autogenerated file. Changes made here will be overwritten.  ##
##                                                              ##
##################################################################

Boatswain:
  ImageTag: "{{.ImageTag}}"
  ServiceEnv:
    {{- range $key, $value := .Env }}
    {{ $key | ToEnv }}: {{ $value }}
	{{- end }}

`)
	var doc bytes.Buffer
	err = tmpl.Execute(&doc, yaml)
	s := doc.String()

	if err != nil {
		panic(err)
	}
	return s
}

func createValuesFile(build Build, config Config, yaml string) string {
	fileMode := os.FileMode(0777)
	fileName := "values.staging." + branchName + ".yaml"
	autogenPath := config.Release + "/" + build.Name + "/autogenerated/"
	if !pathExists(autogenPath) {
		os.Mkdir(autogenPath, fileMode)
	}
	valuesPath := autogenPath + fileName
	printWrapper("Creating : " + fileName)
	printWrapper("Created values file: " + valuesPath)

	err := ioutil.WriteFile(valuesPath, []byte(yaml), fileMode)
	if err != nil {
		panic(err)
	}
	return valuesPath
}

func genIngress(build Build) {
	cmdFactory := &factories.CommandFactory{}

	tmpl, _ := template.New("ingress_host").Parse(serviceMapConfig.Ingress.Template)
	var doc bytes.Buffer
	ingressName := struct {
		BranchName string
	}{branchName}
	err := tmpl.Execute(&doc, ingressName)
	if err != nil {
		panic(err)
	}
	ingressHost := doc.String()
	args := []string{ingressHost}

	options := GenIngressFlags{
		Service:     branchName + "-" + serviceMapConfig.Ingress.Service,
		EnableTLS:   false,
		ServicePort: serviceMapConfig.Ingress.Port,
	}

	RunGenIngress(args, cmdFactory, options)
}

func getServiceMap() {
	//get the service serviceMap file
	path := viper.GetString("release") //TODO: capitalize this
	fullPath := path + "/.servicemap/staging.yaml"
	valuesBytes, err := ioutil.ReadFile(fullPath)

	if err != nil {
		panic(err)
	}

	err = yaml.Unmarshal(valuesBytes, &serviceMapConfig)
	if err != nil {
		panic(err)
	}

	for _, sMap := range serviceMapConfig.ServiceMaps {
		if serviceMapName == sMap.Name {
			serviceMap = sMap
		}
	}
}

func convertMapToEnvVars(serviceMap ServiceMap) map[string]string {
	env := make(map[string]string)

	for _, testSvc := range serviceMap.Test {
		env[testSvc] = branchName + "-" + testSvc
	}

	for _, stagingSvc := range serviceMap.Staging {
		env[stagingSvc] = "staging-" + stagingSvc
	}

	return env
}

func getSelectedBuilds(config Config) []Build {
	var builds []Build
	for _, testSvc := range serviceMap.Test {
		for _, build := range config.Builds {
			if testSvc == build.Name {
				builds = append(builds, build)
			}
		}
	}
	return builds
}

type ServiceMapConfig struct {
	ServiceMaps []ServiceMap      `yaml:"ServiceMaps"`
	Ingress     ServiceMapIngress `yaml:"Ingress"`
}

type ServiceMap struct {
	Name    string   `yaml:"Name"`
	Test    []string `yaml:"Test"`
	Staging []string `yaml:"Staging"`
}

type ServiceMapIngress struct {
	Template string `yaml:"Template"`
	Service  string `yaml:"Service"`
	Port     string `yaml:"Port"`
}

func RunStageDelete(args []string) {
	//TODO: very crude... make this better
	domain := args[0]
	out, err := exec.Command("helm", "delete", domain+"-medbridge").CombinedOutput()
	if err != nil {
		fmt.Printf("%s", err)
	} else {
		fmt.Printf("%s", out)
	}

	out, err = exec.Command("kubectl", "delete", "ing", domain+".k8staging.medbridgeeducation.com").CombinedOutput()
	if err != nil {
		fmt.Printf("%s", err)
	} else {
		fmt.Printf("%s", out)
	}
	path := viper.GetString("release")
	stagingFile := path + "/medbridge/autogenerated/values.staging." + domain + ".yaml"
	err = os.Remove(stagingFile)
	if err != nil {
		panic(err)
	}
}
